### PR TITLE
2022 oscars nominees

### PR DESCRIPTION
**Pull request by RikBoeykens**

### CODE REVIEW

**Comment by kyle-n** [comment]
Thanks for adding this year's nominees! 

Could you:

* base this off the latest commit in `random-oscars/main`? 
* Drop all the changes except the JSON file for this year's nominees? 
* Navigate to the root of the project and run `npx prettier --write .`? Requires node, will format the JSON like the other files

**Comment by RikBoeykens** [comment]
I'm not really used to working with forks and such... Trying to figure out how to do the stuff you asked for

**Comment by kyle-n** [comment]
No worries! Git's obtuse. These aren't exact commands, but from a high level, here's what you want to be doing:

- Update your fork of the repo by pulling the latest from the `main` branch of `random-oscars/random-oscars.github.io`. 
- Check out a new branch from that and run the scraper. That'll generate a bunch of new JSON files, but commit only the JSON file for this year's Oscars. Discard the rest of the changes (`git checkout -- (whatever files)`)
- [Install node](https://nodejs.org/en/download/)
- Navigate to your project directory root from the command line and run `npx prettier --write .`. If it asks if you want to install prettier, say yes.
- Only the new JSON file should be changed by prettier.
- Push up your branch and create the PR. 

You'll know everything worked if you check the "Files Changed" page and the only diff is the new JSON file for this year's nominees. 

Let me know if that helps. We can jump on Discord or some messaging service if you need help.

**Comment by RikBoeykens** [comment]
I'm pretty busy at the moment, hope to have a look at it by the end of the week!

**Pull request closed without merging**
